// Command generate-schema downloads the Fingerprint OpenAPI YAML spec and generates
// a Go file containing the JSON schema for the get_event tool's output.
package main

import (
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

const (
	openapiURL                = "https://raw.githubusercontent.com/fingerprintjs/fingerprint-pro-server-api-openapi/refs/heads/main/schemas/fingerprint-server-api-for-sdks.yaml"
	outputGoFile              = "schema_generated.go"
	outputJSONFile            = "openapi_defs.json"
	searchEventsInputJSONFile = "search_events_input.json"
	productsFieldsJSONFile    = "products_fields.json"
	// rootSchemas lists the OpenAPI schemas to include (with transitive dependencies)
	rootSchemas = "EventsGetResponse,SearchEventsResponse"
)

func main() {
	spec, err := downloadSpec()
	if err != nil {
		log.Fatalf("Error downloading spec: %v", err)
	}

	schemas := extractSchemas(spec)

	// Collect all transitively referenced schemas starting from the root schema(s)
	collected := map[string]any{}
	for _, root := range strings.Split(rootSchemas, ",") {
		root = strings.TrimSpace(root)
		if root != "" {
			collectRefs(schemas, root, collected)
		}
	}

	// Clean up OpenAPI-specific fields and rewrite $refs
	for name, schema := range collected {
		collected[name] = cleanSchema(schema)
	}

	jsonBytes, err := json.MarshalIndent(collected, "", "  ")
	if err != nil {
		log.Fatalf("Error marshaling JSON: %v", err)
	}

	// Write the JSON file containing just the $defs
	if err := os.WriteFile(outputJSONFile, jsonBytes, 0644); err != nil {
		log.Fatalf("Error writing JSON file: %v", err)
	}

	// Extract search events input schema from OpenAPI parameters
	searchInputSchema, err := buildSearchEventsInputSchema(spec)
	if err != nil {
		log.Fatalf("Error building search events input schema: %v", err)
	}

	searchInputBytes, err := json.MarshalIndent(searchInputSchema, "", "  ")
	if err != nil {
		log.Fatalf("Error marshaling search events input schema: %v", err)
	}

	if err := os.WriteFile(searchEventsInputJSONFile, searchInputBytes, 0644); err != nil {
		log.Fatalf("Error writing search events input JSON file: %v", err)
	}

	// Extract Products schema property names for field selection enum
	productsFields := extractProductsFields(collected)
	productsFieldsBytes, err := json.MarshalIndent(productsFields, "", "  ")
	if err != nil {
		log.Fatalf("Error marshaling products fields: %v", err)
	}

	if err := os.WriteFile(productsFieldsJSONFile, productsFieldsBytes, 0644); err != nil {
		log.Fatalf("Error writing products fields JSON file: %v", err)
	}

	// Generate SearchEventInput struct from OpenAPI parameters
	searchEventInputStruct, err := generateSearchEventInputStruct(spec)
	if err != nil {
		log.Fatalf("Error generating SearchEventInput struct: %v", err)
	}

	// Write the generated Go file that embeds the JSON and includes the struct
	goSrc := `// Code generated by cmd/generate-schema; DO NOT EDIT.
package main

import (
	_ "embed"
	"encoding/json"
)

//go:embed openapi_defs.json
var openAPIDefs json.RawMessage

//go:embed search_events_input.json
var searchEventsInputSchema json.RawMessage

//go:embed products_fields.json
var productsFields json.RawMessage

` + searchEventInputStruct

	if err := os.WriteFile(outputGoFile, []byte(goSrc), 0644); err != nil {
		log.Fatalf("Error writing Go file: %v", err)
	}

	log.Printf("Generated %s, %s, %s, and %s with %d schema definitions", outputGoFile, outputJSONFile, searchEventsInputJSONFile, productsFieldsJSONFile, len(collected))
}

func downloadSpec() (map[string]any, error) {
	resp, err := http.Get(openapiURL)
	if err != nil {
		return nil, fmt.Errorf("fetching OpenAPI spec: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("unexpected status %d fetching OpenAPI spec", resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("reading response body: %w", err)
	}

	var spec map[string]any
	if err := yaml.Unmarshal(body, &spec); err != nil {
		return nil, fmt.Errorf("parsing YAML: %w", err)
	}

	return spec, nil
}

func extractSchemas(spec map[string]any) map[string]any {
	components, ok := spec["components"].(map[string]any)
	if !ok {
		return nil
	}
	schemas, ok := components["schemas"].(map[string]any)
	if !ok {
		return nil
	}
	return schemas
}

// buildSearchEventsInputSchema extracts the parameters from the /events/search GET endpoint
// and converts them into a JSON Schema object.
func buildSearchEventsInputSchema(spec map[string]any) (map[string]any, error) {
	paths, ok := spec["paths"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing paths in spec")
	}
	eventsSearch, ok := paths["/events/search"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing /events/search path in spec")
	}
	getOp, ok := eventsSearch["get"].(map[string]any)
	if !ok {
		return nil, fmt.Errorf("missing GET operation on /events/search")
	}
	params, ok := getOp["parameters"].([]any)
	if !ok {
		return nil, fmt.Errorf("missing parameters on /events/search GET")
	}

	properties := make(map[string]any)
	var required []string

	for _, p := range params {
		param, ok := p.(map[string]any)
		if !ok {
			continue
		}
		name, _ := param["name"].(string)
		if name == "" {
			continue
		}

		propSchema := make(map[string]any)

		// Copy the parameter's schema fields (type, format, enum, etc.)
		if schema, ok := param["schema"].(map[string]any); ok {
			for k, v := range schema {
				if shouldRemoveField(k) {
					continue
				}
				propSchema[k] = v
			}
		}

		// Add description from the parameter level
		if desc, ok := param["description"].(string); ok && desc != "" {
			propSchema["description"] = desc
		}

		properties[name] = propSchema

		// Check if parameter is required
		if req, ok := param["required"].(bool); ok && req {
			required = append(required, name)
		}
	}

	sort.Strings(required)

	schema := map[string]any{
		"type":                 "object",
		"properties":           properties,
		"additionalProperties": false,
	}
	if len(required) > 0 {
		schema["required"] = required
	}

	return schema, nil
}

// collectRefs recursively collects all schemas referenced from the given root schema name.
func collectRefs(allSchemas map[string]any, name string, collected map[string]any) {
	if _, exists := collected[name]; exists {
		return
	}
	schema, ok := allSchemas[name]
	if !ok {
		return
	}
	collected[name] = schema
	// Find all $ref values in this schema and collect those too
	refs := findRefs(schema)
	for _, ref := range refs {
		refName := extractSchemaName(ref)
		if refName != "" {
			collectRefs(allSchemas, refName, collected)
		}
	}
}

// findRefs recursively finds all $ref string values in a structure.
func findRefs(v any) []string {
	var refs []string
	switch val := v.(type) {
	case map[string]any:
		if ref, ok := val["$ref"].(string); ok {
			refs = append(refs, ref)
		}
		// Sort keys for deterministic output
		keys := make([]string, 0, len(val))
		for k := range val {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			refs = append(refs, findRefs(val[k])...)
		}
	case []any:
		for _, item := range val {
			refs = append(refs, findRefs(item)...)
		}
	}
	return refs
}

// extractSchemaName extracts the schema name from a $ref like "#/components/schemas/Foo".
func extractSchemaName(ref string) string {
	const prefix = "#/components/schemas/"
	if strings.HasPrefix(ref, prefix) {
		return strings.TrimPrefix(ref, prefix)
	}
	return ""
}

// cleanSchema recursively cleans a schema by removing OpenAPI-specific fields,
// rewriting $ref paths, and handling nullable.
func cleanSchema(v any) any {
	switch val := v.(type) {
	case map[string]any:
		result := make(map[string]any, len(val))

		// Handle nullable before processing other fields
		nullable := false
		if n, ok := val["nullable"]; ok {
			if b, ok := n.(bool); ok && b {
				nullable = true
			}
		}

		for k, v := range val {
			if shouldRemoveField(k) {
				continue
			}
			if k == "$ref" {
				if ref, ok := v.(string); ok {
					result["$ref"] = rewriteRef(ref)
				}
				continue
			}
			result[k] = cleanSchema(v)
		}

		// Handle nullable: convert type string to array including "null"
		if nullable {
			if t, ok := result["type"].(string); ok {
				result["type"] = []any{t, "null"}
			}
		}

		return result
	case []any:
		result := make([]any, len(val))
		for i, item := range val {
			result[i] = cleanSchema(item)
		}
		return result
	default:
		return v
	}
}

// shouldRemoveField returns true for OpenAPI-specific fields not valid in JSON Schema.
func shouldRemoveField(field string) bool {
	switch field {
	case "example", "xml", "discriminator", "externalDocs", "nullable", "deprecated":
		return true
	}
	// Remove vendor extensions (x-* fields)
	if strings.HasPrefix(field, "x-") {
		return true
	}
	return false
}

// extractProductsFields returns the sorted property names of the "Products" schema.
func extractProductsFields(schemas map[string]any) []string {
	products, ok := schemas["Products"]
	if !ok {
		return nil
	}
	pm, ok := products.(map[string]any)
	if !ok {
		return nil
	}
	props, ok := pm["properties"].(map[string]any)
	if !ok {
		return nil
	}
	fields := make([]string, 0, len(props))
	for k := range props {
		fields = append(fields, k)
	}
	sort.Strings(fields)
	return fields
}

// generateSearchEventInputStruct reads /events/search GET parameters from the OpenAPI spec
// and generates a Go struct definition for SearchEventInput.
func generateSearchEventInputStruct(spec map[string]any) (string, error) {
	paths, ok := spec["paths"].(map[string]any)
	if !ok {
		return "", fmt.Errorf("missing paths in spec")
	}
	eventsSearch, ok := paths["/events/search"].(map[string]any)
	if !ok {
		return "", fmt.Errorf("missing /events/search path in spec")
	}
	getOp, ok := eventsSearch["get"].(map[string]any)
	if !ok {
		return "", fmt.Errorf("missing GET operation on /events/search")
	}
	params, ok := getOp["parameters"].([]any)
	if !ok {
		return "", fmt.Errorf("missing parameters on /events/search GET")
	}

	// Collect required parameter names
	requiredSet := map[string]bool{}
	for _, p := range params {
		param, ok := p.(map[string]any)
		if !ok {
			continue
		}
		name, _ := param["name"].(string)
		if req, ok := param["required"].(bool); ok && req {
			requiredSet[name] = true
		}
	}

	type fieldDef struct {
		goName  string
		goType  string
		jsonTag string
	}

	var fields []fieldDef

	for _, p := range params {
		param, ok := p.(map[string]any)
		if !ok {
			continue
		}
		name, _ := param["name"].(string)
		if name == "" {
			continue
		}

		schema, _ := param["schema"].(map[string]any)
		typeName, _ := schema["type"].(string)
		format, _ := schema["format"].(string)
		isRequired := requiredSet[name]

		goType := openAPITypeToGo(typeName, format, isRequired, schema)
		goName := snakeToPascal(name)

		jsonTag := name
		if !isRequired {
			jsonTag += ",omitempty"
		}

		fields = append(fields, fieldDef{
			goName:  goName,
			goType:  goType,
			jsonTag: jsonTag,
		})
	}

	// Append custom Products field
	fields = append(fields, fieldDef{
		goName:  "Products",
		goType:  "[]string",
		jsonTag: "products,omitempty",
	})

	// Find max goName length for alignment
	maxNameLen := 0
	for _, f := range fields {
		if len(f.goName) > maxNameLen {
			maxNameLen = len(f.goName)
		}
	}

	var buf strings.Builder
	buf.WriteString("type SearchEventInput struct {\n")
	for _, f := range fields {
		padding := strings.Repeat(" ", maxNameLen-len(f.goName)+1)
		buf.WriteString(fmt.Sprintf("\t%s%s%s `json:\"%s\"`\n", f.goName, padding, f.goType, f.jsonTag))
	}
	buf.WriteString("}\n")

	return buf.String(), nil
}

// openAPITypeToGo maps an OpenAPI type+format to a Go type string.
func openAPITypeToGo(typeName, format string, required bool, schema map[string]any) string {
	switch typeName {
	case "boolean":
		if required {
			return "bool"
		}
		return "*bool"
	case "string":
		if required {
			return "string"
		}
		return "*string"
	case "integer":
		if required {
			return "int"
		}
		switch format {
		case "int64":
			return "*int64"
		case "int32":
			return "*int32"
		default:
			return "*int"
		}
	case "number":
		if required {
			return "float64"
		}
		switch format {
		case "float":
			return "*float32"
		default:
			return "*float64"
		}
	case "array":
		items, _ := schema["items"].(map[string]any)
		itemType, _ := items["type"].(string)
		switch itemType {
		case "string":
			return "[]string"
		default:
			return "[]any"
		}
	default:
		return "any"
	}
}

// snakeToPascal converts a snake_case string to PascalCase.
// It uses simple first-letter capitalization (not Go abbreviation conventions)
// to match the field names in the Fingerprint SDK's generated structs
// (e.g. VisitorId, IpAddress, SdkVersion — not VisitorID, IPAddress, SDKVersion).
func snakeToPascal(s string) string {
	parts := strings.Split(s, "_")
	var buf strings.Builder
	for _, part := range parts {
		if len(part) == 0 {
			continue
		}
		buf.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return buf.String()
}

// rewriteRef rewrites OpenAPI $ref paths to JSON Schema $defs paths.
func rewriteRef(ref string) string {
	const prefix = "#/components/schemas/"
	if strings.HasPrefix(ref, prefix) {
		name := strings.TrimPrefix(ref, prefix)
		return "#/$defs/" + name
	}
	return ref
}
