// Code generated by cmd/generate-schema; DO NOT EDIT.
package schema

import (
	_ "embed"
	"encoding/json"
)

//go:embed openapi_defs.json
var openAPIDefs json.RawMessage

//go:embed search_events_input.json
var SearchEventsInputSchema json.RawMessage

//go:embed products_fields.json
var productsFields json.RawMessage

type SearchEventInput struct {
	Limit                    int      `json:"limit"`
	PaginationKey            *string  `json:"pagination_key,omitempty"`
	VisitorId                *string  `json:"visitor_id,omitempty"`
	Bot                      *string  `json:"bot,omitempty"`
	IpAddress                *string  `json:"ip_address,omitempty"`
	LinkedId                 *string  `json:"linked_id,omitempty"`
	Start                    *int64   `json:"start,omitempty"`
	End                      *int64   `json:"end,omitempty"`
	Reverse                  *bool    `json:"reverse,omitempty"`
	Suspect                  *bool    `json:"suspect,omitempty"`
	Vpn                      *bool    `json:"vpn,omitempty"`
	VirtualMachine           *bool    `json:"virtual_machine,omitempty"`
	Tampering                *bool    `json:"tampering,omitempty"`
	AntiDetectBrowser        *bool    `json:"anti_detect_browser,omitempty"`
	Incognito                *bool    `json:"incognito,omitempty"`
	PrivacySettings          *bool    `json:"privacy_settings,omitempty"`
	Jailbroken               *bool    `json:"jailbroken,omitempty"`
	Frida                    *bool    `json:"frida,omitempty"`
	FactoryReset             *bool    `json:"factory_reset,omitempty"`
	ClonedApp                *bool    `json:"cloned_app,omitempty"`
	Emulator                 *bool    `json:"emulator,omitempty"`
	RootApps                 *bool    `json:"root_apps,omitempty"`
	VpnConfidence            *string  `json:"vpn_confidence,omitempty"`
	MinSuspectScore          *float32 `json:"min_suspect_score,omitempty"`
	IpBlocklist              *bool    `json:"ip_blocklist,omitempty"`
	Datacenter               *bool    `json:"datacenter,omitempty"`
	DeveloperTools           *bool    `json:"developer_tools,omitempty"`
	LocationSpoofing         *bool    `json:"location_spoofing,omitempty"`
	MitmAttack               *bool    `json:"mitm_attack,omitempty"`
	Proxy                    *bool    `json:"proxy,omitempty"`
	SdkVersion               *string  `json:"sdk_version,omitempty"`
	SdkPlatform              *string  `json:"sdk_platform,omitempty"`
	Environment              []string `json:"environment,omitempty"`
	ProximityId              *string  `json:"proximity_id,omitempty"`
	ProximityPrecisionRadius *int32   `json:"proximity_precision_radius,omitempty"`
	Products                 []string `json:"products,omitempty"`
}
