// Code generated by cmd/generate-schema; DO NOT EDIT.
package schema

import (
	_ "embed"
	"encoding/json"
)

//go:embed openapi_defs.json
var openAPIDefs json.RawMessage

//go:embed search_events_input.json
var SearchEventsInputSchema json.RawMessage

//go:embed products_fields.json
var productsFields json.RawMessage

type SearchEventInput struct {
	Limit             *int32   `json:"limit,omitempty"`
	PaginationKey     *string  `json:"pagination_key,omitempty"`
	VisitorId         *string  `json:"visitor_id,omitempty"`
	Bot               any      `json:"bot,omitempty"`
	IpAddress         *string  `json:"ip_address,omitempty"`
	Asn               *string  `json:"asn,omitempty"`
	LinkedId          *string  `json:"linked_id,omitempty"`
	Url               *string  `json:"url,omitempty"`
	BundleId          *string  `json:"bundle_id,omitempty"`
	PackageName       *string  `json:"package_name,omitempty"`
	Origin            *string  `json:"origin,omitempty"`
	Start             *int64   `json:"start,omitempty"`
	End               *int64   `json:"end,omitempty"`
	Reverse           *bool    `json:"reverse,omitempty"`
	Suspect           *bool    `json:"suspect,omitempty"`
	Vpn               *bool    `json:"vpn,omitempty"`
	VirtualMachine    *bool    `json:"virtual_machine,omitempty"`
	Tampering         *bool    `json:"tampering,omitempty"`
	AntiDetectBrowser *bool    `json:"anti_detect_browser,omitempty"`
	Incognito         *bool    `json:"incognito,omitempty"`
	PrivacySettings   *bool    `json:"privacy_settings,omitempty"`
	Jailbroken        *bool    `json:"jailbroken,omitempty"`
	Frida             *bool    `json:"frida,omitempty"`
	FactoryReset      *bool    `json:"factory_reset,omitempty"`
	ClonedApp         *bool    `json:"cloned_app,omitempty"`
	Emulator          *bool    `json:"emulator,omitempty"`
	RootApps          *bool    `json:"root_apps,omitempty"`
	VpnConfidence     any      `json:"vpn_confidence,omitempty"`
	MinSuspectScore   *float32 `json:"min_suspect_score,omitempty"`
	DeveloperTools    *bool    `json:"developer_tools,omitempty"`
	LocationSpoofing  *bool    `json:"location_spoofing,omitempty"`
	MitmAttack        *bool    `json:"mitm_attack,omitempty"`
	Proxy             *bool    `json:"proxy,omitempty"`
	SdkVersion        *string  `json:"sdk_version,omitempty"`
	SdkPlatform       any      `json:"sdk_platform,omitempty"`
	Environment       []string `json:"environment,omitempty"`
	ProximityId       *string  `json:"proximity_id,omitempty"`
	TotalHits         *int64   `json:"total_hits,omitempty"`
	TorNode           *bool    `json:"tor_node,omitempty"`
	Products          []string `json:"products,omitempty"`
}
