package schema

import (
	"bytes"
	"encoding/json"
	"regexp"
	"strings"
	"time"
)

// rfc3339Millis keeps the millisecond precision the API sends. Dropping to
// whole seconds would silently lose ordering between events in the same second,
// which is common on a busy visitor.
const rfc3339Millis = "2006-01-02T15:04:05.000Z07:00"

// epochMillisFields are the response fields the Fingerprint API returns as Unix
// epoch milliseconds. Every name here is unique to a timestamp across the whole
// event shape, so matching on the key alone can't hit an unrelated number.
//
// factory_reset_timestamp is deliberately absent. The API documents 0 on that
// field as "no factory reset detected, or the request came from a browser", so
// it is a timestamp-or-sentinel rather than an instant. Converting it would
// render that 0 as 1970-01-01, a real-looking date for something that never
// happened, which is the exact misreading this conversion exists to prevent.
// Leaving the value alone while still retyping the schema produced a payload
// that contradicted its own schema, so it stays an integer end to end.
var epochMillisFields = map[string]bool{
	"timestamp":     true,
	"first_seen_at": true,
	"last_seen_at":  true,
}

// ReadableTimestamps re-encodes v with every epoch-millisecond field rewritten
// as an RFC3339 string.
//
// The reason is that the reader is a language model. `1786458425180` forces it
// to divide by a thousand and convert in its head to answer "when did this
// happen", and it reliably gets that wrong: read as seconds it lands in 1970,
// and an off-by-1000 lands decades out. GROW-601 fixed the same problem on the
// request side by taking RFC3339 for `start`/`end`; this is the response half.
//
// v is returned unchanged if it can't be round-tripped through JSON, since a
// readable timestamp is never worth failing a tool call over.
func ReadableTimestamps(v any) any {
	b, err := json.Marshal(v)
	if err != nil {
		return v
	}
	dec := json.NewDecoder(bytes.NewReader(b))
	// Numbers stay as text until we choose to interpret them, so a large
	// millisecond value can't lose precision on the way through float64.
	dec.UseNumber()

	var decoded any
	if err := dec.Decode(&decoded); err != nil {
		return v
	}
	return rewriteTimestamps(decoded)
}

// epochMillisDefs are top-level $defs that are themselves an epoch-millisecond
// integer. Event.timestamp is a $ref to one of these rather than an inline
// property, so matching on the property name alone misses it entirely.
//
// FactoryReset is deliberately absent, matching epochMillisFields above.
var epochMillisDefs = map[string]bool{
	"Timestamp": true,
}

// embeddedExample strips the epoch example the upstream spec writes into the
// description text, e.g. "… first seen. example: `1758069706642` - Corresponding
// to Wed Sep 17 2025 …". It isn't an `example` key, so it survives deleting
// those and then contradicts the type. Everything from the example onward goes,
// because what follows it is prose restating the same epoch value as a date.
var embeddedExample = regexp.MustCompile("(?s)\\s*example:\\s*`?\\d{10,}`?.*$")

// unitPhrases rewrites the upstream wording, which names milliseconds. The
// phrasing differs per field because it comes from the OpenAPI spec verbatim;
// each is replaced in place so the rest of the sentence, which carries the
// actual meaning of the field, survives.
var unitPhrases = strings.NewReplacer(
	"Unix epoch time milliseconds timestamp", "RFC3339 timestamp",
	"Unix epoch timestamp (in milliseconds)", "RFC3339 timestamp",
	"Unix millisecond timestamp", "RFC3339 timestamp",
	"with millisecond precision in Unix time", "as an RFC3339 string with millisecond precision",
)

// PatchTimestampFormat rewrites the epoch-millisecond fields in a JSON schema
// to the string/date-time form that ReadableTimestamps actually emits.
//
// The generated defs come from the upstream OpenAPI spec and are regenerated by
// cmd/generate-schema, so they can't be corrected in place; this patches the
// served copy instead, the same way PatchProductsEnum does.
func PatchTimestampFormat(raw json.RawMessage) json.RawMessage {
	var doc any
	if err := json.Unmarshal(raw, &doc); err != nil {
		return raw
	}
	patchTimestampFormat(doc)

	patched, err := json.Marshal(doc)
	if err != nil {
		return raw
	}
	return patched
}

func patchTimestampFormat(v any) {
	switch t := v.(type) {
	case map[string]any:
		for k, child := range t {
			prop, ok := child.(map[string]any)
			if ok && (epochMillisFields[k] || epochMillisDefs[k]) && prop["type"] == "integer" {
				patchTimestampProperty(prop)
				continue
			}
			patchTimestampFormat(child)
		}
	case []any:
		for _, child := range t {
			patchTimestampFormat(child)
		}
	}
}

func patchTimestampProperty(prop map[string]any) {
	prop["type"] = "string"
	prop["format"] = "date-time"
	if desc, ok := prop["description"].(string); ok {
		desc = unitPhrases.Replace(desc)
		prop["description"] = strings.TrimSpace(embeddedExample.ReplaceAllString(desc, ""))
	}
	// Epoch examples contradict the type once it's a string.
	delete(prop, "example")
	delete(prop, "examples")
}

func rewriteTimestamps(v any) any {
	switch t := v.(type) {
	case map[string]any:
		for k, child := range t {
			if epochMillisFields[k] {
				if s, ok := epochMillisToRFC3339(child); ok {
					t[k] = s
					continue
				}
			}
			t[k] = rewriteTimestamps(child)
		}
		return t
	case []any:
		for i, child := range t {
			t[i] = rewriteTimestamps(child)
		}
		return t
	default:
		return v
	}
}

// epochMillisToRFC3339 converts a JSON number of milliseconds since the epoch.
// It reports false for anything it can't read as a whole number, and for zero,
// which the API uses to mean "no value" rather than midnight in 1970.
func epochMillisToRFC3339(v any) (string, bool) {
	n, ok := v.(json.Number)
	if !ok {
		return "", false
	}
	ms, err := n.Int64()
	if err != nil || ms == 0 {
		return "", false
	}
	return time.UnixMilli(ms).UTC().Format(rfc3339Millis), true
}
